name: dio_intercept_to_curl_example
description: Demonstrates how to use the dio_intercept_to_curl plugin.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"
dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter

  dio_intercept_to_curl:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true