name: dio_intercept_to_curl
description: Intercept dio requests and print them as curl requests
version: 0.0.7
homepage: https://github.com/LastxTemplar/dio_intercept_to_curl

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  dio: ^5.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
