name: dio_intercept_to_curl
description: Intercept Dio requests and print them as curl commands in the debug panel. Easily paste the request in your terminal to run it again. Use it to easily debug your Dio request.
version: 0.1.0
homepage: https://github.com/LastxTemplar/dio_intercept_to_curl

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  dio: ^5.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
